### ISSUE TITLE
Restructure files

### ISSUE THREAD

**Issue by nanokind** [regularjs/regular-devtools#34]
`src/devtools-ui`

**给extension和electron提供核心的界面**，需要和chrome.* api和electron api解耦，打包到dist目录，和`src/extension`和`src/electron`组合后，在`release`目录生成chrome扩展和electron应用

`src/extension`

**chrome扩展相关代码**，如manifest.json, background.js, inject.js, regular.png...

`src/electron`

**electron相关代码**

@zxc0328 你觉得怎么样？

**Comment by zxc0328** [comment]
可以的。移动设备的远程调试现在的确很麻烦，如果调试的内核支持Chrome Devtools Protocol的话，还是用electron写一个壳比较好。所以把代码结构调整一下把平台无关的抽出来是必要的。

用electron写其实也是可以用在PC端的浏览器上的。可以补充一下Chrome Devtool拓展这种形式无法和浏览器使用Chrome Devtools Protocol通信的遗憾（因为Chrome Devtools已经占了端口了）。有些Devtools的原生方法比如DOM高亮，还要一些内存性能方面的API都可以用。

**Comment by nanokind** [comment]
嗯，如果你还有代码没提交趁现在提交下，我等会就调整下目录

**Comment by nanokind** [comment]
@zxc0328 其实我的想法是用electron起一个server，需要往页面的head中插一个外链的脚本，Chrome Devtools Protocol的局限性太大了，有些app的webview不支持

> 可以补充一下Chrome Devtool拓展这种形式无法和浏览器使用Chrome Devtools Protocol通信的遗憾（因为Chrome Devtools已经占了端口了）

我记得chrome扩展可以通过chrome.debugger.* api和chrome使用Chrome Devtools Protocol通信的

**Comment by zxc0328** [comment]
好的，我的意思是如果有比较高级的，不是非常必要的需求可以用Chrome Devtools Protocol做。一般的操作肯定还是注入脚本和server用socket通信这样吧。我这边现在没有代码提交了。

因为Chrome Devtools也是用那个协议的，所以打开Devtools的情况下就没法再开一个新的连接了。文档里有说：

> As of today, attaching to the tab by means of the debugger API and using embedded Chrome DevTools with that tab are mutually exclusive. If user invokes Chrome DevTools while extension is attached to the tab, debugging session is terminated. Extension can re-establish it later.

**Comment by nanokind** [comment]
嗯，明白了，那我开工啦😬
