### ISSUE TITLE
新增特性

### ISSUE THREAD

**Issue by nanokind** [regularjs/regular-devtools#4]
在可行的前提下增加以下features：
- 支持将组件的data或实例打印到控制台(参考vue-devtools + React-Devtools)
- 支持按组件名字进行过滤(参考React-Devtools + vue-devtools)
- 在右侧data处增加一栏events，用于记录event历史，并给每个event标记触发时间，支持清空
- 如果一个组件没有定义name属性，使用在父组件中定义的名字，Parent.component( 'foo', bar )，比如这个例子中，使用foo，如果有其他未考虑到的匿名组件情形使用anonymous
- 支持修改data并实时更新视图，支持undo(参考React-Devtools)
  
  > 可以用上面提到的第一个特性代替，将组件实例打印在控制台，用户手动修改data并调用$update，但这样交互会好些

@zxc0328 你的想法呢？

**Comment by zxc0328** [comment]
@fengzilong  

> 支持将组件的data或实例打印到控制台(参考vue-devtools + React-Devtools)
> 支持按组件名字进行过滤(参考React-Devtools + vue-devtools)

这个可以做

> 支持修改data并实时更新视图，支持undo(参考React-Devtools)

现在是单向的，应该改成双向的。就是修改data之后可以更新页面上的组件。undo这个感觉要加一层model，类似redux的，成本有点大，初始的版本先不考虑吧。

> 如果一个组件没有定义name属性，使用在父组件中定义的名字，Parent.component( 'foo', bar )，比如这个例子中，使用foo，如果有其他未考虑到的匿名组件情形使用anonymous

这个因为我对Regular其实不是很熟。我看到的组件大都是用标签引入的，所以都有name。的确应该考虑的更全面一些。因为引入组件有很多办法。

**Comment by zxc0328** [comment]
@fengzilong 

之前和教育产品部的陈钦辉同学讨论，他提了几点建议：
- 右边的data可以用Chrome Devtools自带的那种树形视图，自带编辑功能。
- 右边应该不只显示data，还应该显示watchers和指令等组件的相关属性。
- 把当前组件打印到控制台，这个和你的想法一样。
- 他还提了一些构想，比如可以查看脏检查性能相关的数据。

**Comment by nanokind** [comment]
@zxc0328 

> 支持修改data并实时更新视图，支持undo

这里的undo只是撤销用户对data的修改，只要针对单个组件维护一份修改历史就好了，所以应该没想象中那么复杂，同意这个放后面

> 如果一个组件没有定义name属性，使用在父组件中定义的名字，Parent.component( 'foo', bar )，比如这个例子中，使用foo，如果有其他未考虑到的匿名组件情形使用anonymous

regularjs官方是建议**用时定义名字**的，和引用一个模块一样，在require的时候再给这个模块一个名字，这个还是有必要支持一下的

**Comment by nanokind** [comment]
@zxc0328 

> 右边的data可以用Chrome Devtools自带的那种树形视图，自带编辑功能。

这个树形组件估计只能我们自己做了，没有发现可以在独立devtools panel中使用那个视图的api，如果是我没看到的话，麻烦指出

> 右边应该不只显示data，还应该显示watchers和指令等组件的相关属性。

说到这个，想起来一件事，目前好像是没把computed属性展示在data中的，这个也要加一下

> 他还提了一些构想，比如可以查看脏检查性能相关的数据。

这个可以有
