### ISSUE TITLE
1.0版计划

### ISSUE THREAD

**Issue by zxc0328** [regularjs/regular-devtools#7]
- [x] include显示优化 一行 赵
- [x] 选中组件把实例输出到控制台 赵
- [x] tab组件 冯
- [x] data tab显示computed属性 冯
- [x] data属性可以编辑，页面组件更新 冯
- [x] others tab显示指令 filter 和动画 陈
- [x] 搜索组件 高亮 赵
- [x] 组件名 没有name属性则在parent上找 赵

**Comment by nanokind** [comment]
暂定8月底之前完成这些features吧:smirk:

**Comment by nanokind** [comment]
已经全部完成了，先关掉吧~

**Comment by zxc0328** [comment]
我现在在学校，时间还是比较多的。要不要讨论一下接下去的改进计划？

**Comment by nanokind** [comment]
@zxc0328  好的，下周一的时候泡泡上联系下吧～

**Comment by zxc0328** [comment]
我泡泡被注销了··· 微信联系吧，Hg0328

**Comment by nanokind** [comment]
...已加
